### ISSUE TITLE
El test de Feature#02 esta fallando

### ISSUE THREAD

**Issue by GameEngineers** [GameEngineers/SpaiEcp2JorgeGarridoEstevez#10]
Revisar por que está fallando el test de Feature#02. Puede haber un problema en la función **_Fraction.divide(...)**_ o en el test. Por otra parte el Test debería poder realizarse usando assertEquals(...) si se apoya en en las funciones getNumerator() y getDenominator().
Un saludo!

**Comment by jimeneztion** [comment]
El test anterior esta correcto,pero se cambia el test utilizando assertEquals. Test OK

**Comment by GameEngineers** [comment]
Hora Sergio, 
He detectado un error en la función divide(...), no esta implementada correctamente aun que esta funcionando correctamente el test. Debería de poder resolverse. Arregla el test en consecuencia.
Mira la explicación de la divisin de fracciones en los comentarios de la propia clase.
Un saludo!

**Comment by jimeneztion** [comment]
buenas,
Equivacacion al implantar el metodo. Solucionado

**Comment by GameEngineers** [comment]
Ok Sergio, He comprobado y la funcionalidad es correcta.
Gracias!

---

Elimine el mensaje sin darme cuenta, lo replico de nuevo:

Hora Sergio, 
He detectado un error en la función divide(...), no esta implementada correctamente aun que esta funcionando correctamente el test. Debería de poder resolverse. Arregla el test en consecuencia.
Mira la explicación de la divisin de fracciones en los comentarios de la propia clase.
Un saludo!
